### PR TITLE
Support rails 5

### PR DESCRIPTION
**Pull request by iloveitaly**

### CODE REVIEW

**Comment by iloveitaly** [comment]
@AlessioRocco I rebased this on master and ensured tests are passing. Is there anything you'd like to see on this one?

**Comment by AlessioRocco** [comment]
@iloveitaly do you think we can implement a way to easily switch tests for rails 4.x and 5.x?

**Comment by iloveitaly** [comment]
With the changes in this PR, travis-ci will test both rails4 + rails5 based on the current `RUBY_VERSION`. In development, I've been modifying the `Gemfile` to test different rails versions.

@AlessioRocco I'm not aware of a better way to handle this... any ideas on your end? How do other projects handle this problem?

**Comment by AlessioRocco** [comment]
I've merged this one for now, then I plan to improve the specs with something like https://github.com/thoughtbot/appraisal

**Pull request merged**
