### PR TITLE
Response formatting improvement

### PR DESCRIPTION
**Pull request by iloveitaly**

### CODE REVIEW

**Comment by AlessioRocco** [comment]
@iloveitaly I'm not sure we should handle the `201` and `202`, Cangaroo come from Wombat and it doesn't handle these status codes (if I remember well), we must be sure that adding these status codes allow the integrations to work like before and don't introduce some strange behaviors or errors.

**Comment by iloveitaly** [comment]
@AlessioRocco I don't think this change is backwards incompatible with Wombat. Wombat endpoints either return `200` or framework-generated 4xx and 5xx error codes. 2xx indicates a successful response from an endpoint, so I think it makes sense for cangaroo to gracefully handle any error codes in the 2xx range.

Is there a specific use-case you are worried about breaking?

Thanks for thinking through this change!

**Comment by AlessioRocco** [comment]
@iloveitaly merged, after some thinking I've no found incompatibilities with Wombat. Thanks 👍

**Comment by iloveitaly** [comment]
@AlessioRocco Awesome, thanks Alessio!

**Pull request merged**
