### PR TITLE
Structured logging

### PR DESCRIPTION
**Pull request by iloveitaly**
Initial stab at an improved audit trail for the app.

I have some additional logging statements I'd like to merge into this PR, but it's dependent on some of the other PRs I have open. Once those are merged, I'll update this PR with the relevant logging statements.

### CODE REVIEW

**Comment by iloveitaly** [comment]
@AlessioRocco any thoughts on this PR, @AlessioRocco?

**Comment by AlessioRocco** [comment]
@iloveitaly looks good to me, can you please rebase master with latest changes to specs?

**Comment by iloveitaly** [comment]
@AlessioRocco done!

**Comment by AlessioRocco** [comment]
@iloveitaly 👍

**Pull request merged**
